10 snake game
6im0n/Arcade pull request #28
Opened 2024-03-21 14:02 UTC by Njord201

2024-03-22 13:02 UTC, Quentintnrl commented on classes/Timer.cpp
plutôt que de mettre des fonctions vide met "= 0" ou "= default" dans le .hpp

2024-03-22 13:04 UTC, Quentintnrl commented on core/Core.cpp
> +        if (_key_event == Arcade::Keys::O || _key_event == Arcade::Keys::P
Ce n'est pas nécessaire de préciser le namespace étant donné que la class Core est déjà dedans

2024-03-22 13:04 UTC, Quentintnrl commented on src/snake/Entities/Color.cpp
> +Color::~Color()
Pareil pour le "= default"

2024-03-22 13:05 UTC, Quentintnrl commented on src/snake/Entities/Food.cpp
> +
saut de ligne inutile

2024-03-22 13:06 UTC, Quentintnrl commented on src/snake/Entities/Food.cpp
> +    _pos = randomPos(snake);
la position initiale de la pomme dans le jeu snake est fixe

2024-03-22 13:06 UTC, Quentintnrl commented on src/snake/Entities/Food.cpp
> +{
= default

2024-03-22 13:07 UTC, Quentintnrl commented on src/snake/Entities/SnakeBody.cpp
> +SnakeBody::~SnakeBody()
= default

2024-03-22 13:08 UTC, Quentintnrl commented on src/snake/Entities/Void.cpp
> +Void::~Void()
= default

2024-03-22 13:09 UTC, Quentintnrl commented on src/snake/Entities/Wall.cpp
> +Wall::~Wall()
= default

2024-03-22 13:09 UTC, Quentintnrl commented on src/snake/Snake.cpp
> +Snake::~Snake()
= default

2024-03-22 13:14 UTC, Quentintnrl commented on src/snake/Snake.hpp
> +        Direction _dir;
tu peux la renomer "direction" ?

2024-03-22 13:16 UTC, Quentintnrl commented on src/snake/SnakeGame.cpp
> +SnakeGame::~SnakeGame()
= default

2024-03-22 13:18 UTC, Quentintnrl commented on src/snake/SnakeGame.cpp
> +int SnakeGame::stopGame()
C'est normal que "stopGame" laisse le jeu tel quel ou c'est que ce n'est pas encore dev ?

2024-03-22 13:20 UTC, Quentintnrl commented on tests/testDLLoader.cpp
Est-ce que tu peux créer de nouveaux tests plutôt que de modifier ceux-là ?

2024-03-22 13:21 UTC, Quentintnrl requested changes
lire commentaires

2024-03-22 14:29 UTC, Njord201 commented on src/snake/Entities/Food.cpp
> +    _pos = randomPos(snake);
Non ?

![image](https://github.com/6im0n/Arcade/assets/114904525/5017ae75-15fe-465c-9735-ab7083160b55)

2024-03-22 14:32 UTC, Njord201 commented on tests/testDLLoader.cpp
J'ai juste corrigé les tests conformément a ce qui a été dit dans Shared-Arcade

2024-03-22 14:35 UTC, Quentintnrl commented on tests/testDLLoader.cpp
pardon alors j'ai du mal lire

2024-03-22 14:44 UTC, Njord201 commented on src/snake/Entities/Food.cpp
> +    _pos = randomPos(snake);
https://snake.googlemaps.com/

2024-03-23 09:34 UTC, Quentintnrl approved these changes

2024-03-25 09:08 UTC, 6im0n approved these changes
✔️Good for me

2024-03-25 10:41 UTC, merged