8 button of the menu
6im0n/Arcade pull request #62
Opened 2024-03-29 16:02 UTC by Quentintnrl

2024-03-29 17:01 UTC, Njord201 requested changes
Voir les commentaires, et tu as des erreurs de compilation sur le jeu Snake.

2024-03-29 17:01 UTC, Njord201 commented on src/snake/SnakeGame.hpp
> -
Pourquoi enlevé le retour a la ligne ?

2024-04-01 09:58 UTC, Quentintnrl commented on Makefile
> +CC				= g++ -std=c++20
J'avais un doute sur l'utilisation de la lib j'ai voulu forcé la compilation avec pour être sur que le problème ne venait pas de là
Je le remet au niveau des flags

2024-04-01 10:02 UTC, Quentintnrl commented on src/ncurses/ncurses.hpp
> +            Ncurses();
C'était pour des tests autant laissé les fonctions comme ça vu qu'on va devoir les créer après

2024-04-01 10:02 UTC, Quentintnrl commented on src/snake/Entities/SnakeBody.cpp
> +Arcade::SnakeBody::SnakeBody(std::size_t x, std::size_t y)
non c'est une erreur lors de la résolution des conflits

2024-04-01 10:02 UTC, Quentintnrl commented on src/snake/Snake.hpp
pareil problème de résolution de conflits

2024-04-02 11:01 UTC, 6im0n commented on core/main.cpp
>  }
Missing Line break.

2024-04-02 11:07 UTC, 6im0n reviewed
Aprés les changements demandés, c'est good !

2024-04-02 11:10 UTC, 6im0n reviewed
Aprés les modifs demandés, c'est good !

2024-04-02 11:10 UTC, 6im0n commented on core/main.cpp
>  }
Missing Line break.

2024-04-02 11:10 UTC, 6im0n commented on lib/topScores.txt
no need to push the score ?

2024-04-02 12:48 UTC, Njord201 requested changes
Tu n'as pas fait tous les changements de la review précédente + quelques request en plus

2024-04-02 12:48 UTC, Njord201 commented on classes/Text.cpp
> +std::string Arcade::Text::getFontPath()
N'oublie pas le const

2024-04-02 12:48 UTC, Njord201 commented on classes/Text.cpp
> +std::string Arcade::Text::getText()
const

2024-04-02 12:48 UTC, Njord201 commented on src/ncurses/ncurses.hpp
> +            Ncurses();
Je comprends mais mettre dès maintenant le default, ça évitera à Simon de l'oublier si il ne modifie pas le constructeur par la suite, c'est surtout pour les destructeur que je voulais faire ça.

2024-04-02 12:51 UTC, Quentintnrl commented on core/DLLoader.hpp
Parce que j'utilise un template

2024-04-02 16:32 UTC, 6im0n approved these changes
OK good

2024-04-02 16:37 UTC, 6im0n commented
OK

2024-04-02 16:37 UTC, 6im0n approved these changes

2024-04-02 18:13 UTC, Njord201 commented on core/DLLoader.hpp
Il faut déclarer la méthode comme ça dans le cpp :

```cpp
     T *Arcade::DLLoader<T>::getInstance(const std::string &libname)
```
N'oublie pas de reprécisé le `template <typename<T>>` avant

2024-04-02 18:13 UTC, Quentintnrl commented on core/Core.cpp
> +        } else if (_key_event != Keys::UNKNOWN) {
C'est pas important au pire on ajoute ça à la fin

2024-04-02 18:13 UTC, Quentintnrl commented on core/Core.hpp
>  //key O = previous game
c'est pour du debug

2024-04-02 18:14 UTC, Njord201 commented on src/ncurses/ncurses.hpp
> +            Ncurses();
Oui je suis d'accord

2024-04-02 18:17 UTC, Quentintnrl commented on core/menu/Button.hpp
> +            Button *getNextButton();
C'est pour une liste chainée je vais tout bloquer sinon

2024-04-02 18:17 UTC, Quentintnrl commented on core/menu/Button.hpp
> +            Button *getPrevButton();
C'est pour une liste chainée je vais tout bloquer sinon

2024-04-02 18:17 UTC, Quentintnrl commented on core/menu/Button.hpp
> +            Button *getUpButton();
C'est pour une liste chainée je vais tout bloquer sinon

2024-04-02 18:17 UTC, Quentintnrl commented on core/menu/Button.hpp
> +            Button *getDownButton();
C'est pour une liste chainée je vais tout bloquer sinon

2024-04-02 18:18 UTC, Quentintnrl commented on lib/topScores.txt
Parce qu'il faut qu'il soit là à l'initialisation

2024-04-02 21:28 UTC, Njord201 reviewed
C'est bon pour, si peux virer rapidement le debug inutile et c'est ok

2024-04-02 21:29 UTC, Njord201 approved these changes

2024-04-02 21:30 UTC, merged